clear; clc; close all;

% Define wind speed range for the x-axis (0 to 30 m/s)
v = 0:0.1:30; 

% Turbine: Vestas V162-6.2 MW
Pr1  = 6.2;     % Rated power (MW)
Vci1 = 3;       % Cut-in wind speed (m/s)
Vr1  = 10.5;    % Rated wind speed (m/s)
Vco1 = 24;      % Cut-out wind speed (m/s)

P1 = zeros(size(v)); % Preallocate power array

% Apply piecewise cubic equation (Eq. 2)
idx_ramp1 = (v >= Vci1) & (v < Vr1);
idx_rated1 = (v >= Vr1) & (v < Vco1);

P1(idx_ramp1) = Pr1 * ((v(idx_ramp1).^3 - Vci1^3) ./ (Vr1^3 - Vci1^3));
P1(idx_rated1) = Pr1;

% Plotting the curve
figure('Name', 'Wind Turbine Power Curve', 'Position', [100, 100, 700, 500]);

% Plot turbine
plot(v, P1, 'LineWidth', 2.5, 'Color', '#0072BD'); 
hold on;

% Formatting the plot
grid on;
set(gca, ...
    'GridAlpha', 0.3, ...
    'FontSize', 12, ...
    'FontWeight', 'bold', ...
    'LineWidth', 1.5, ...
    'XColor', 'k', ...
    'YColor', 'k', ...
    'Box', 'on');

xlabel('Wind Speed (m/s)', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Output Power (MW)', 'FontSize', 12, 'FontWeight', 'bold');
title('Power–Wind Speed Curve for the Vestas V162-6.2 MW Turbine', ...
      'FontSize', 14, 'FontWeight', 'bold');

% Add legend and deepen it
lgd = legend('Vestas V162-6.2 MW', 'Location', 'NorthWest', 'FontSize', 11);
set(lgd, ...
    'TextColor', 'k', ...
    'FontWeight', 'bold', ...
    'LineWidth', 1.2, ...
    'EdgeColor', 'k', ...
    'Color', 'w');

% Set axis limits
xlim([0 30]);
ylim([0 7]);

% Add darker vertical lines for cut-in, rated, and cut-out speeds
xline(Vci1, 'k:', 'Cut-in (3 m/s)', ...
      'LineWidth', 1.5, ...
      'FontSize', 11, ...
      'FontWeight', 'bold', ...
      'LabelVerticalAlignment', 'bottom', ...
      'HandleVisibility', 'off');

xline(Vr1, 'k:', 'Rated (10.5 m/s)', ...
      'LineWidth', 1.5, ...
      'FontSize', 11, ...
      'FontWeight', 'bold', ...
      'LabelVerticalAlignment', 'bottom', ...
      'LabelHorizontalAlignment', 'left', ...
      'HandleVisibility', 'off');

xline(Vco1, 'k:', 'Cut-out (24 m/s)', ...
      'LineWidth', 1.5, ...
      'FontSize', 11, ...
      'FontWeight', 'bold', ...
      'LabelVerticalAlignment', 'bottom', ...
      'HandleVisibility', 'off');

hold off;